defaults:
  - default
  - ../train@train: tiny54
  - ../diffusion@diffusion: v1
  - _self_

model_path: './test/tiny54/'  # Path to trained model
diff_ckpt: 'OliBomby/osu-diffusion-v2'
version: 'Mapperatorinator tiny54'
in_context: []
output_type: [TIMING, MAP, SV]    # Output type (map, timing)
temperature: 0.9        # Sampling temperature
top_p: 0.9              # Top-p sampling threshold
max_batch_size: 32       # Maximum batch size for inference
generate_positions: false