defaults:
  - default
  - _self_

name: 'Tiger14n/ropewhisper-small'
input_features: true
project_encoder_input: false

do_style_embed: false
do_difficulty_embed: false
do_mapper_embed: false
do_song_position_embed: false
cond_dim: 128
cond_size: 0

spectrogram:
  implementation: 'torchaudio'
  log_scale: true
  n_mels: 128
  f_min: 20
  pad_mode: 'reflect'

overwrite:
  tie_word_embeddings: false
  d_model: 640
  decoder_attention_heads: 10
  decoder_ffn_dim: 2560
  decoder_layers: 9
  encoder_attention_heads: 10
  encoder_ffn_dim: 2560
  encoder_layers: 9